name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app:${{ steps.vars.outputs.TAG }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app:latest \
            --push .

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Blue/Green + Nginx switch (real)
        run: |
          TAG=${{ needs.build.outputs.tag }}
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app

          echo "Deployando versión $TAG"

          # Detectar backend activo
          ACTIVE=$(grep -o 'app_[a-z]*' /home/adminpi/actions-runner/active_backend.conf)

          if [ "$ACTIVE" = "app_blue" ]; then
            NEW="app_green"
          else
            NEW="app_blue"
          fi

          echo "Activo: $ACTIVE"
          echo "Nuevo: $NEW"

          # Pull imagen
          docker pull $IMAGE:$TAG

          # Levantar nueva versión
          docker rm -f $NEW || true
          docker run -d \
            --name $NEW \
            --network devops-net \
            $IMAGE:$TAG

          # Esperar healthcheck
          echo "Esperando health..."

          for i in {1..10}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' $NEW 2>/dev/null || echo "fail")

            echo "Intento $i - Estado: $STATUS"

            if [ "$STATUS" = "healthy" ]; then
              echo "Nueva versión OK"
              break
            fi

            if [ "$STATUS" = "unhealthy" ]; then
              echo "Nueva versión falló"
              break
            fi

            sleep 10
          done

          # Si falla → abortar
          if [ "$STATUS" != "healthy" ]; then
            echo "❌ Deploy cancelado"
            docker rm -f $NEW
            exit 1
          fi

          # Switch nginx (ACÁ ESTÁ LA MAGIA)
          echo "🔄 Switcheando tráfico a $NEW"

          echo "server $NEW:5000;" > /home/adminpi/actions-runner/active_backend.conf

          docker exec nginx nginx -s reload

          # Borrar viejo
          docker rm -f $ACTIVE || true

          echo "✅ Deploy sin downtime real"
